a=int(input("輸入西元年:"))
if(a%12==4):
    print("鼠")
elif(a%12==5):
    print("牛")
elif(a%12==6):
    print("虎")
elif(a%12==7):
    print("兔")
elif(a%12==8):
    print("龍")
elif(a%12==9):
    print("蛇")
elif(a%12==10):
    print("馬")
elif(a%12==11):
    print("羊")
elif(a%12==0):
    print("猴")
elif(a%12==1):
    print("雞")
elif(a%12==2):
    print("狗")
elif(a%12==3):
    print("豬")